# Generated by Django 4.2.5 on 2023-09-28 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddapp', '0003_customuser_bio_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 27, 22, 2, 54, 142667)),
        ),
    ]
